{% set name = "python-sonarqube-api" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b7a785c10d4ae3532c592f6dfe3b5cc4cf489888c2995d822e5f80fdb8259219

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - sonarqube

about:
  home: https://github.com/shijl0925/python-sonarqube-api
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for the SonarQube and SonarCloud API

extra:
  recipe-maintainers:
    - kevingovaerts
    - JFreitas9
