{% set name = "python-sonarqube-api" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c475425899af60df39c67c93192d124e76d2315b8f4ca65aea6fb14416e506c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools
  run:
    - python >=2.7
    - requests

test:
  imports:
    - sonarqube

about:
  home: https://github.com/shijl0925/python-sonarqube-api
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for the SonarQube and SonarCloud API

extra:
  recipe-maintainers:
    - kevingovaerts
    - JFreitas9
