{% set name = "python-sonarqube-api" %}
{% set version = "1.1.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2592d4acdc7577c30813fecb554b29ed625ba2fc809919edc0eab30876a3d4e1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools
  run:
    - python >=2.7
    - requests

test:
  imports:
    - sonarqube

about:
  home: https://github.com/shijl0925/python-sonarqube-api
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for the SonarQube and SonarCloud API

extra:
  recipe-maintainers:
    - JFreitas9
