{% set name = "python-sonarqube-api" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d4fadac2c81a1cae2d5ab033acda5d87ed2710b19e6ee1f266482d9ed553c155

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools
  run:
    - python >=2.7
    - requests

test:
  imports:
    - sonarqube

about:
  home: https://github.com/shijl0925/python-sonarqube-api
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for the SonarQube and SonarCloud API

extra:
  recipe-maintainers:
    - kevingovaerts
    - JFreitas9
