{% set name = "python-sonarqube-api" %}
{% set version = "1.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bea1eda64d21c24d7c7650db81bd1deb7dc9f0ebc98b2e12fa2c21eab208e1fa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=2.7
    - pip
    - setuptools
  run:
    - python >=2.7
    - requests

test:
  imports:
    - sonarqube

about:
  home: https://github.com/shijl0925/python-sonarqube-api
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for the SonarQube and SonarCloud API

extra:
  recipe-maintainers:
    - kevingovaerts
    - JFreitas9
